FROM golang:1.26.2-alpine3.23 AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o app

FROM scratch

WORKDIR /app

COPY --from=builder /app/app .

CMD ["./app"]