// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aliases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryDeleteStackAlias = `-- name: QueryDeleteStackAlias :exec
DELETE FROM stack_aliases
WHERE id = $1
`

func (q *Queries) QueryDeleteStackAlias(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, queryDeleteStackAlias, id)
	return err
}

const queryInsertStackAlias = `-- name: QueryInsertStackAlias :one
INSERT INTO stack_aliases(alias_from, alias_to)
VALUES ($1, $2)
RETURNING id, alias_from, alias_to, created_at
`

type QueryInsertStackAliasParams struct {
	AliasFrom string `json:"alias_from"`
	AliasTo   string `json:"alias_to"`
}

func (q *Queries) QueryInsertStackAlias(ctx context.Context, arg QueryInsertStackAliasParams) (StackAlias, error) {
	row := q.db.QueryRow(ctx, queryInsertStackAlias, arg.AliasFrom, arg.AliasTo)
	var i StackAlias
	err := row.Scan(
		&i.ID,
		&i.AliasFrom,
		&i.AliasTo,
		&i.CreatedAt,
	)
	return i, err
}

const querySelectAllStackAliases = `-- name: QuerySelectAllStackAliases :many
SELECT alias_from, alias_to FROM stack_aliases
`

type QuerySelectAllStackAliasesRow struct {
	AliasFrom string `json:"alias_from"`
	AliasTo   string `json:"alias_to"`
}

func (q *Queries) QuerySelectAllStackAliases(ctx context.Context) ([]QuerySelectAllStackAliasesRow, error) {
	rows, err := q.db.Query(ctx, querySelectAllStackAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuerySelectAllStackAliasesRow
	for rows.Next() {
		var i QuerySelectAllStackAliasesRow
		if err := rows.Scan(&i.AliasFrom, &i.AliasTo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectAllStackAliasesWithID = `-- name: QuerySelectAllStackAliasesWithID :many
SELECT id, alias_from, alias_to FROM stack_aliases
ORDER BY alias_from
`

type QuerySelectAllStackAliasesWithIDRow struct {
	ID        pgtype.UUID `json:"id"`
	AliasFrom string      `json:"alias_from"`
	AliasTo   string      `json:"alias_to"`
}

func (q *Queries) QuerySelectAllStackAliasesWithID(ctx context.Context) ([]QuerySelectAllStackAliasesWithIDRow, error) {
	rows, err := q.db.Query(ctx, querySelectAllStackAliasesWithID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuerySelectAllStackAliasesWithIDRow
	for rows.Next() {
		var i QuerySelectAllStackAliasesWithIDRow
		if err := rows.Scan(&i.ID, &i.AliasFrom, &i.AliasTo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
