// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryInsertFeedback = `-- name: QueryInsertFeedback :exec
INSERT INTO resumes_feedback(resume_id, user_id, status, comments)
VALUES ($1, $2, $3, $4)
`

type QueryInsertFeedbackParams struct {
	ResumeID pgtype.UUID    `json:"resume_id"`
	UserID   pgtype.UUID    `json:"user_id"`
	Status   FeedbackStatus `json:"status"`
	Comments pgtype.Text    `json:"comments"`
}

func (q *Queries) QueryInsertFeedback(ctx context.Context, arg QueryInsertFeedbackParams) error {
	_, err := q.db.Exec(ctx, queryInsertFeedback,
		arg.ResumeID,
		arg.UserID,
		arg.Status,
		arg.Comments,
	)
	return err
}

const querySelectExcellentResumes = `-- name: QuerySelectExcellentResumes :many
SELECT gr.content_json
FROM resumes_feedback rf
JOIN generated_resumes gr ON gr.id = rf.resume_id
WHERE
    rf.status = 'excellent' AND
    rf.user_id = $1
ORDER BY rf.created_at DESC
LIMIT 3
`

func (q *Queries) QuerySelectExcellentResumes(ctx context.Context, userID pgtype.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, querySelectExcellentResumes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var content_json []byte
		if err := rows.Scan(&content_json); err != nil {
			return nil, err
		}
		items = append(items, content_json)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectFeedbackByResume = `-- name: QuerySelectFeedbackByResume :one
SELECT id, resume_id, user_id, status, comments, created_at FROM resumes_feedback
WHERE resume_id = $1 AND user_id = $2
`

type QuerySelectFeedbackByResumeParams struct {
	ResumeID pgtype.UUID `json:"resume_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) QuerySelectFeedbackByResume(ctx context.Context, arg QuerySelectFeedbackByResumeParams) (ResumesFeedback, error) {
	row := q.db.QueryRow(ctx, querySelectFeedbackByResume, arg.ResumeID, arg.UserID)
	var i ResumesFeedback
	err := row.Scan(
		&i.ID,
		&i.ResumeID,
		&i.UserID,
		&i.Status,
		&i.Comments,
		&i.CreatedAt,
	)
	return i, err
}

const querySelectGoodFeedbacks = `-- name: QuerySelectGoodFeedbacks :many
SELECT rf.comments
FROM resumes_feedback rf
WHERE
    rf.status IN ('good', 'fair') AND
    rf.comments IS NOT NULL AND
    rf.user_id = $1
ORDER BY rf.created_at DESC
LIMIT 5
`

func (q *Queries) QuerySelectGoodFeedbacks(ctx context.Context, userID pgtype.UUID) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, querySelectGoodFeedbacks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var comments pgtype.Text
		if err := rows.Scan(&comments); err != nil {
			return nil, err
		}
		items = append(items, comments)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
