// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: filters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryDeleteFilter = `-- name: QueryDeleteFilter :exec
DELETE FROM user_job_filters
WHERE id = $1 AND user_id = $2
`

type QueryDeleteFilterParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryDeleteFilter(ctx context.Context, arg QueryDeleteFilterParams) error {
	_, err := q.db.Exec(ctx, queryDeleteFilter, arg.ID, arg.UserID)
	return err
}

const queryInsertFilter = `-- name: QueryInsertFilter :one
INSERT INTO user_job_filters(user_id, keyword)
VALUES ($1, $2)
RETURNING id, user_id, keyword, created_at, updated_at, deleted_at
`

type QueryInsertFilterParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Keyword string      `json:"keyword"`
}

func (q *Queries) QueryInsertFilter(ctx context.Context, arg QueryInsertFilterParams) (UserJobFilter, error) {
	row := q.db.QueryRow(ctx, queryInsertFilter, arg.UserID, arg.Keyword)
	var i UserJobFilter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Keyword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const querySelectFiltersForUser = `-- name: QuerySelectFiltersForUser :many
SELECT keyword FROM user_job_filters
WHERE user_id = $1
`

func (q *Queries) QuerySelectFiltersForUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, querySelectFiltersForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var keyword string
		if err := rows.Scan(&keyword); err != nil {
			return nil, err
		}
		items = append(items, keyword)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectFiltersForUserWithID = `-- name: QuerySelectFiltersForUserWithID :many
SELECT id, keyword, user_id, COUNT(*) OVER() AS total_count FROM user_job_filters
WHERE user_id = $1
ORDER BY keyword
LIMIT $3 OFFSET $2
`

type QuerySelectFiltersForUserWithIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Cursor int32       `json:"cursor"`
	Size   int32       `json:"size"`
}

type QuerySelectFiltersForUserWithIDRow struct {
	ID         pgtype.UUID `json:"id"`
	Keyword    string      `json:"keyword"`
	UserID     pgtype.UUID `json:"user_id"`
	TotalCount int64       `json:"total_count"`
}

func (q *Queries) QuerySelectFiltersForUserWithID(ctx context.Context, arg QuerySelectFiltersForUserWithIDParams) ([]QuerySelectFiltersForUserWithIDRow, error) {
	rows, err := q.db.Query(ctx, querySelectFiltersForUserWithID, arg.UserID, arg.Cursor, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuerySelectFiltersForUserWithIDRow
	for rows.Next() {
		var i QuerySelectFiltersForUserWithIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Keyword,
			&i.UserID,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
