// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryDeleteJob = `-- name: QueryDeleteJob :exec
DELETE FROM jobs 
WHERE id = $1 
AND user_id = $2
`

type QueryDeleteJobParams struct {
	JobID  pgtype.UUID `json:"job_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryDeleteJob(ctx context.Context, arg QueryDeleteJobParams) error {
	_, err := q.db.Exec(ctx, queryDeleteJob, arg.JobID, arg.UserID)
	return err
}

const queryDeleteResume = `-- name: QueryDeleteResume :exec
DELETE FROM generated_resumes
WHERE id = $1 AND user_id = $2
`

type QueryDeleteResumeParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryDeleteResume(ctx context.Context, arg QueryDeleteResumeParams) error {
	_, err := q.db.Exec(ctx, queryDeleteResume, arg.ID, arg.UserID)
	return err
}

const queryFindJobByUrl = `-- name: QueryFindJobByUrl :one
SELECT j.id FROM jobs j
WHERE j.external_url = $1 AND j.user_id = $2
`

type QueryFindJobByUrlParams struct {
	ExternalUrl string      `json:"external_url"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryFindJobByUrl(ctx context.Context, arg QueryFindJobByUrlParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, queryFindJobByUrl, arg.ExternalUrl, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const queryInsertFullJob = `-- name: QueryInsertFullJob :one
INSERT INTO jobs(external_url, user_id, company_name, job_title, description,
    tech_stack, requirements, language)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8
) RETURNING id
`

type QueryInsertFullJobParams struct {
	ExternalUrl  string      `json:"external_url"`
	UserID       pgtype.UUID `json:"user_id"`
	CompanyName  pgtype.Text `json:"company_name"`
	JobTitle     pgtype.Text `json:"job_title"`
	Description  pgtype.Text `json:"description"`
	TechStack    []string    `json:"tech_stack"`
	Requirements []string    `json:"requirements"`
	Language     pgtype.Text `json:"language"`
}

func (q *Queries) QueryInsertFullJob(ctx context.Context, arg QueryInsertFullJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, queryInsertFullJob,
		arg.ExternalUrl,
		arg.UserID,
		arg.CompanyName,
		arg.JobTitle,
		arg.Description,
		arg.TechStack,
		arg.Requirements,
		arg.Language,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const queryInsertUrlJob = `-- name: QueryInsertUrlJob :one
INSERT INTO jobs(external_url, user_id)
VALUES ($1, $2) RETURNING id
`

type QueryInsertUrlJobParams struct {
	ExternalUrl string      `json:"external_url"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryInsertUrlJob(ctx context.Context, arg QueryInsertUrlJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, queryInsertUrlJob, arg.ExternalUrl, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const queryListResumesForUser = `-- name: QueryListResumesForUser :many
SELECT
    gr.id, gr.job_id, gr.resume_pdf_path, gr.cover_letter_path, gr.created_at, gr.content_json,
    j.company_name, j.job_title, j.quality,
    COUNT(*) OVER() AS total_count
FROM generated_resumes gr
JOIN jobs j ON j.id = gr.job_id
WHERE gr.user_id = $1 AND j.id = $2
ORDER BY gr.created_at DESC
LIMIT $4 OFFSET $3
`

type QueryListResumesForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	JobID  pgtype.UUID `json:"job_id"`
	Cursor int32       `json:"cursor"`
	Size   int32       `json:"size"`
}

type QueryListResumesForUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	JobID           pgtype.UUID        `json:"job_id"`
	ResumePdfPath   pgtype.Text        `json:"resume_pdf_path"`
	CoverLetterPath pgtype.Text        `json:"cover_letter_path"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ContentJson     []byte             `json:"content_json"`
	CompanyName     pgtype.Text        `json:"company_name"`
	JobTitle        pgtype.Text        `json:"job_title"`
	Quality         NullJobQuality     `json:"quality"`
	TotalCount      int64              `json:"total_count"`
}

func (q *Queries) QueryListResumesForUser(ctx context.Context, arg QueryListResumesForUserParams) ([]QueryListResumesForUserRow, error) {
	rows, err := q.db.Query(ctx, queryListResumesForUser,
		arg.UserID,
		arg.JobID,
		arg.Cursor,
		arg.Size,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryListResumesForUserRow
	for rows.Next() {
		var i QueryListResumesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ResumePdfPath,
			&i.CoverLetterPath,
			&i.CreatedAt,
			&i.ContentJson,
			&i.CompanyName,
			&i.JobTitle,
			&i.Quality,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryReprocessJob = `-- name: QueryReprocessJob :exec
UPDATE jobs
SET
    status     = 'pending',
    updated_at = now()
WHERE id = $1 AND user_id = $2
`

type QueryReprocessJobParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryReprocessJob(ctx context.Context, arg QueryReprocessJobParams) error {
	_, err := q.db.Exec(ctx, queryReprocessJob, arg.ID, arg.UserID)
	return err
}

const querySelectJobsForUser = `-- name: QuerySelectJobsForUser :many
SELECT j.id, j.user_id, j.external_url, j.company_name, j.job_title, j.description, j.tech_stack, j.requirements, j.status, j.quality, j.language, j.created_at, j.updated_at, j.deleted_at, COUNT(*) OVER() AS total_count
FROM jobs j
INNER JOIN user_accounts acc ON acc.id = j.user_id
WHERE
    j.user_id = $1 AND
    j.deleted_at IS NULL AND
    acc.deleted_at IS NULL
ORDER BY j.created_at DESC
LIMIT $3 OFFSET $2
`

type QuerySelectJobsForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Cursor int32       `json:"cursor"`
	Size   int32       `json:"size"`
}

type QuerySelectJobsForUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ExternalUrl  string             `json:"external_url"`
	CompanyName  pgtype.Text        `json:"company_name"`
	JobTitle     pgtype.Text        `json:"job_title"`
	Description  pgtype.Text        `json:"description"`
	TechStack    []string           `json:"tech_stack"`
	Requirements []string           `json:"requirements"`
	Status       JobStatus          `json:"status"`
	Quality      NullJobQuality     `json:"quality"`
	Language     pgtype.Text        `json:"language"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	TotalCount   int64              `json:"total_count"`
}

func (q *Queries) QuerySelectJobsForUser(ctx context.Context, arg QuerySelectJobsForUserParams) ([]QuerySelectJobsForUserRow, error) {
	rows, err := q.db.Query(ctx, querySelectJobsForUser, arg.UserID, arg.Cursor, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuerySelectJobsForUserRow
	for rows.Next() {
		var i QuerySelectJobsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExternalUrl,
			&i.CompanyName,
			&i.JobTitle,
			&i.Description,
			&i.TechStack,
			&i.Requirements,
			&i.Status,
			&i.Quality,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectResumeJob = `-- name: QuerySelectResumeJob :one
SELECT 
    gr.id, gr.content_json, gr.resume_pdf_path, gr.cover_letter_path,
    j.company_name, j.job_title, j.language, j.quality
FROM generated_resumes gr
JOIN jobs j ON j.id = gr.job_id
WHERE gr.id = $1 AND gr.user_id = $2
`

type QuerySelectResumeJobParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type QuerySelectResumeJobRow struct {
	ID              pgtype.UUID    `json:"id"`
	ContentJson     []byte         `json:"content_json"`
	ResumePdfPath   pgtype.Text    `json:"resume_pdf_path"`
	CoverLetterPath pgtype.Text    `json:"cover_letter_path"`
	CompanyName     pgtype.Text    `json:"company_name"`
	JobTitle        pgtype.Text    `json:"job_title"`
	Language        pgtype.Text    `json:"language"`
	Quality         NullJobQuality `json:"quality"`
}

func (q *Queries) QuerySelectResumeJob(ctx context.Context, arg QuerySelectResumeJobParams) (QuerySelectResumeJobRow, error) {
	row := q.db.QueryRow(ctx, querySelectResumeJob, arg.ID, arg.UserID)
	var i QuerySelectResumeJobRow
	err := row.Scan(
		&i.ID,
		&i.ContentJson,
		&i.ResumePdfPath,
		&i.CoverLetterPath,
		&i.CompanyName,
		&i.JobTitle,
		&i.Language,
		&i.Quality,
	)
	return i, err
}

const queryUpdateJob = `-- name: QueryUpdateJob :exec
UPDATE jobs
SET
    company_name = COALESCE($1, company_name),
    job_title = COALESCE($2, job_title),
    description = COALESCE($3, description),
    tech_stack = COALESCE($4, tech_stack),
    requirements = COALESCE($5, requirements),
    language = COALESCE($6, language)
WHERE
    id = $7 and user_id = $8
`

type QueryUpdateJobParams struct {
	CompanyName  pgtype.Text `json:"company_name"`
	JobTitle     pgtype.Text `json:"job_title"`
	Description  pgtype.Text `json:"description"`
	TechStack    []string    `json:"tech_stack"`
	Requirements []string    `json:"requirements"`
	Language     pgtype.Text `json:"language"`
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryUpdateJob(ctx context.Context, arg QueryUpdateJobParams) error {
	_, err := q.db.Exec(ctx, queryUpdateJob,
		arg.CompanyName,
		arg.JobTitle,
		arg.Description,
		arg.TechStack,
		arg.Requirements,
		arg.Language,
		arg.ID,
		arg.UserID,
	)
	return err
}

const queryUpdateResumePaths = `-- name: QueryUpdateResumePaths :exec
UPDATE generated_resumes
SET 
    resume_pdf_path = $1,
    cover_letter_path = $2
WHERE
    id = $3 AND user_id = $4
`

type QueryUpdateResumePathsParams struct {
	ResumePdfPath   pgtype.Text `json:"resume_pdf_path"`
	CoverLetterPath pgtype.Text `json:"cover_letter_path"`
	ID              pgtype.UUID `json:"id"`
	UserID          pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryUpdateResumePaths(ctx context.Context, arg QueryUpdateResumePathsParams) error {
	_, err := q.db.Exec(ctx, queryUpdateResumePaths,
		arg.ResumePdfPath,
		arg.CoverLetterPath,
		arg.ID,
		arg.UserID,
	)
	return err
}
