// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type NivelHabilidade string

const (
	NivelHabilidadeBasico        NivelHabilidade = "basico"
	NivelHabilidadeIntermediario NivelHabilidade = "intermediario"
	NivelHabilidadeAvancado      NivelHabilidade = "avancado"
	NivelHabilidadeExpert        NivelHabilidade = "expert"
)

func (e *NivelHabilidade) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NivelHabilidade(s)
	case string:
		*e = NivelHabilidade(s)
	default:
		return fmt.Errorf("unsupported scan type for NivelHabilidade: %T", src)
	}
	return nil
}

type NullNivelHabilidade struct {
	NivelHabilidade NivelHabilidade `json:"nivel_habilidade"`
	Valid           bool            `json:"valid"` // Valid is true if NivelHabilidade is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNivelHabilidade) Scan(value interface{}) error {
	if value == nil {
		ns.NivelHabilidade, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NivelHabilidade.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNivelHabilidade) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NivelHabilidade), nil
}

type SensorStatus string

const (
	SensorStatusNORMAL     SensorStatus = "NORMAL"
	SensorStatusALERTA     SensorStatus = "ALERTA"
	SensorStatusEMERGENCIA SensorStatus = "EMERGENCIA"
)

func (e *SensorStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SensorStatus(s)
	case string:
		*e = SensorStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SensorStatus: %T", src)
	}
	return nil
}

type NullSensorStatus struct {
	SensorStatus SensorStatus `json:"sensor_status"`
	Valid        bool         `json:"valid"` // Valid is true if SensorStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSensorStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SensorStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SensorStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSensorStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SensorStatus), nil
}

type StatusFeedback string

const (
	StatusFeedbackMedio     StatusFeedback = "medio"
	StatusFeedbackBom       StatusFeedback = "bom"
	StatusFeedbackExcelente StatusFeedback = "excelente"
)

func (e *StatusFeedback) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusFeedback(s)
	case string:
		*e = StatusFeedback(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusFeedback: %T", src)
	}
	return nil
}

type NullStatusFeedback struct {
	StatusFeedback StatusFeedback `json:"status_feedback"`
	Valid          bool           `json:"valid"` // Valid is true if StatusFeedback is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusFeedback) Scan(value interface{}) error {
	if value == nil {
		ns.StatusFeedback, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusFeedback.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusFeedback) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusFeedback), nil
}

type StatusVaga string

const (
	StatusVagaPendente      StatusVaga = "pendente"
	StatusVagaProcessando   StatusVaga = "processando"
	StatusVagaGerado        StatusVaga = "gerado"
	StatusVagaRevisado      StatusVaga = "revisado"
	StatusVagaEnviado       StatusVaga = "enviado"
	StatusVagaForaDoPerfil  StatusVaga = "fora_do_perfil"
	StatusVagaImprocessavel StatusVaga = "improcessavel"
)

func (e *StatusVaga) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusVaga(s)
	case string:
		*e = StatusVaga(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusVaga: %T", src)
	}
	return nil
}

type NullStatusVaga struct {
	StatusVaga StatusVaga `json:"status_vaga"`
	Valid      bool       `json:"valid"` // Valid is true if StatusVaga is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusVaga) Scan(value interface{}) error {
	if value == nil {
		ns.StatusVaga, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusVaga.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusVaga) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusVaga), nil
}

type Alertum struct {
	ID        int64            `json:"id"`
	SensorID  int64            `json:"sensor_id"`
	Status    SensorStatus     `json:"status"`
	AlertTime pgtype.Timestamp `json:"alert_time"`
}

type Certificaco struct {
	ID        int64       `json:"id"`
	Nome      string      `json:"nome"`
	Emissor   string      `json:"emissor"`
	EmitidoEm pgtype.Date `json:"emitido_em"`
	Codigo    pgtype.Text `json:"codigo"`
	Link      pgtype.Text `json:"link"`
	Tags      []string    `json:"tags"`
}

type CurriculosGerado struct {
	ID              int64            `json:"id"`
	VagaID          int64            `json:"vaga_id"`
	ConteudoJson    []byte           `json:"conteudo_json"`
	ResumePath      pgtype.Text      `json:"resume_path"`
	CoverLetterPath pgtype.Text      `json:"cover_letter_path"`
	CriadoEm        pgtype.Timestamp `json:"criado_em"`
}

type Experiencia struct {
	ID         int64       `json:"id"`
	Empresa    string      `json:"empresa"`
	Cargo      string      `json:"cargo"`
	Descricao  pgtype.Text `json:"descricao"`
	Atual      bool        `json:"atual"`
	DataInicio pgtype.Date `json:"data_inicio"`
	DataFim    pgtype.Date `json:"data_fim"`
	Stack      []string    `json:"stack"`
	Conquistas []string    `json:"conquistas"`
	Tags       []string    `json:"tags"`
}

type Feedback struct {
	ID          int64            `json:"id"`
	CurriculoID int64            `json:"curriculo_id"`
	VagaID      int64            `json:"vaga_id"`
	Status      StatusFeedback   `json:"status"`
	Comentario  pgtype.Text      `json:"comentario"`
	CriadoEm    pgtype.Timestamp `json:"criado_em"`
}

type Filtro struct {
	ID      int64  `json:"id"`
	Keyword string `json:"keyword"`
}

type Formacao struct {
	ID          int64       `json:"id"`
	Instituicao string      `json:"instituicao"`
	Curso       string      `json:"curso"`
	DataInicio  pgtype.Date `json:"data_inicio"`
	DataFim     pgtype.Date `json:"data_fim"`
	Descricao   pgtype.Text `json:"descricao"`
}

type Habilidade struct {
	ID    int64           `json:"id"`
	Nome  string          `json:"nome"`
	Nivel NivelHabilidade `json:"nivel"`
	Tags  []string        `json:"tags"`
}

type Historico struct {
	ID        int64            `json:"id"`
	SensorID  int64            `json:"sensor_id"`
	Value     float64          `json:"value"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type InformacoesBasica struct {
	ID        int64            `json:"id"`
	Nome      string           `json:"nome"`
	Email     string           `json:"email"`
	Telefone  pgtype.Text      `json:"telefone"`
	Linkedin  pgtype.Text      `json:"linkedin"`
	Github    pgtype.Text      `json:"github"`
	Portfolio pgtype.Text      `json:"portfolio"`
	Resumo    pgtype.Text      `json:"resumo"`
	CriadoEm  pgtype.Timestamp `json:"criado_em"`
}

type Projeto struct {
	ID          int64       `json:"id"`
	Nome        string      `json:"nome"`
	Descricao   pgtype.Text `json:"descricao"`
	Link        pgtype.Text `json:"link"`
	Tags        []string    `json:"tags"`
	DataInicio  pgtype.Date `json:"data_inicio"`
	DataFim     pgtype.Date `json:"data_fim"`
	Facultativo bool        `json:"facultativo"`
}

type Sensore struct {
	ID     int64        `json:"id"`
	Nome   string       `json:"nome"`
	Loc    string       `json:"loc"`
	Status SensorStatus `json:"status"`
}

type Vaga struct {
	ID         int64            `json:"id"`
	Url        string           `json:"url"`
	Empresa    pgtype.Text      `json:"empresa"`
	Titulo     pgtype.Text      `json:"titulo"`
	Descricao  pgtype.Text      `json:"descricao"`
	Stack      []string         `json:"stack"`
	Requisitos []string         `json:"requisitos"`
	Status     StatusVaga       `json:"status"`
	CriadoEm   pgtype.Timestamp `json:"criado_em"`
	Idioma     pgtype.Text      `json:"idioma"`
}
