// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type FeedbackStatus string

const (
	FeedbackStatusPoor      FeedbackStatus = "poor"
	FeedbackStatusFair      FeedbackStatus = "fair"
	FeedbackStatusGood      FeedbackStatus = "good"
	FeedbackStatusExcellent FeedbackStatus = "excellent"
)

func (e *FeedbackStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeedbackStatus(s)
	case string:
		*e = FeedbackStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FeedbackStatus: %T", src)
	}
	return nil
}

type NullFeedbackStatus struct {
	FeedbackStatus FeedbackStatus `json:"feedback_status"`
	Valid          bool           `json:"valid"`
}

func (ns *NullFeedbackStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FeedbackStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeedbackStatus.Scan(value)
}

func (ns NullFeedbackStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeedbackStatus), nil
}

type JobQuality string

const (
	JobQualityLow  JobQuality = "low"
	JobQualityMid  JobQuality = "mid"
	JobQualityHigh JobQuality = "high"
)

func (e *JobQuality) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobQuality(s)
	case string:
		*e = JobQuality(s)
	default:
		return fmt.Errorf("unsupported scan type for JobQuality: %T", src)
	}
	return nil
}

type NullJobQuality struct {
	JobQuality JobQuality `json:"job_quality"`
	Valid      bool       `json:"valid"`
}

func (ns *NullJobQuality) Scan(value interface{}) error {
	if value == nil {
		ns.JobQuality, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobQuality.Scan(value)
}

func (ns NullJobQuality) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobQuality), nil
}

type JobStatus string

const (
	JobStatusPending       JobStatus = "pending"
	JobStatusError         JobStatus = "error"
	JobStatusProcessing    JobStatus = "processing"
	JobStatusScrapingBasic JobStatus = "scraping_basic"
	JobStatusScrapingNl    JobStatus = "scraping_nl"
	JobStatusCompleted     JobStatus = "completed"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type SecurityEventType string

const (
	SecurityEventTypeLoginFailed  SecurityEventType = "login_failed"
	SecurityEventTypeRateLimited  SecurityEventType = "rate_limited"
	SecurityEventTypePdfGenerated SecurityEventType = "pdf_generated"
)

func (e *SecurityEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SecurityEventType(s)
	case string:
		*e = SecurityEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for SecurityEventType: %T", src)
	}
	return nil
}

type SkillLevel string

const (
	SkillLevelBasic        SkillLevel = "basic"
	SkillLevelIntermediate SkillLevel = "intermediate"
	SkillLevelAdvanced     SkillLevel = "advanced"
	SkillLevelExpert       SkillLevel = "expert"
)

func (e *SkillLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SkillLevel(s)
	case string:
		*e = SkillLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for SkillLevel: %T", src)
	}
	return nil
}

type ErrorLog struct {
	ID           pgtype.UUID        `json:"id"`
	JobID        pgtype.UUID        `json:"job_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ErrorType    string             `json:"error_type"`
	ErrorMessage string             `json:"error_message"`
	Url          pgtype.Text        `json:"url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type GeneratedResume struct {
	ID              pgtype.UUID        `json:"id"`
	JobID           pgtype.UUID        `json:"job_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ContentJson     []byte             `json:"content_json"`
	ResumePdfPath   pgtype.Text        `json:"resume_pdf_path"`
	CoverLetterPath pgtype.Text        `json:"cover_letter_path"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Job struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ExternalUrl  string             `json:"external_url"`
	CompanyName  pgtype.Text        `json:"company_name"`
	JobTitle     pgtype.Text        `json:"job_title"`
	Description  pgtype.Text        `json:"description"`
	TechStack    []string           `json:"tech_stack"`
	Requirements []string           `json:"requirements"`
	Status       JobStatus          `json:"status"`
	Quality      NullJobQuality     `json:"quality"`
	Language     pgtype.Text        `json:"language"`
	Mode         string             `json:"mode"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type ResumesFeedback struct {
	ID        pgtype.UUID        `json:"id"`
	ResumeID  pgtype.UUID        `json:"resume_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Status    FeedbackStatus     `json:"status"`
	Comments  pgtype.Text        `json:"comments"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SecurityEvent struct {
	ID        pgtype.UUID        `json:"id"`
	EventType SecurityEventType  `json:"event_type"`
	Ip        pgtype.Text        `json:"ip"`
	UserID    pgtype.UUID        `json:"user_id"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type StackAlias struct {
	ID        pgtype.UUID        `json:"id"`
	AliasFrom string             `json:"alias_from"`
	AliasTo   string             `json:"alias_to"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserAcademicHistory struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	InstitutionName string             `json:"institution_name"`
	CourseName      string             `json:"course_name"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	Description     pgtype.Text        `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type UserAccount struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	IsAdmin      bool               `json:"is_admin"`
}

type UserCertificate struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	CertificateName     string             `json:"certificate_name"`
	IssuingOrganization string             `json:"issuing_organization"`
	IssueDate           pgtype.Date        `json:"issue_date"`
	CredentialUrl       pgtype.Text        `json:"credential_url"`
	Tags                []string           `json:"tags"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type UserExperience struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	CompanyName  string             `json:"company_name"`
	JobRole      string             `json:"job_role"`
	Description  pgtype.Text        `json:"description"`
	IsCurrentJob bool               `json:"is_current_job"`
	StartDate    pgtype.Date        `json:"start_date"`
	EndDate      pgtype.Date        `json:"end_date"`
	TechStack    []string           `json:"tech_stack"`
	Achievements []string           `json:"achievements"`
	Tags         []string           `json:"tags"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type UserJobFilter struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Keyword   string             `json:"keyword"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type UserLink struct {
	UserID       pgtype.UUID        `json:"user_id"`
	LinkedinUrl  pgtype.Text        `json:"linkedin_url"`
	GithubUrl    pgtype.Text        `json:"github_url"`
	PortfolioUrl pgtype.Text        `json:"portfolio_url"`
	OtherLinks   []byte             `json:"other_links"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type UserProfile struct {
	UserID       pgtype.UUID        `json:"user_id"`
	FullName     string             `json:"full_name"`
	Phone        pgtype.Text        `json:"phone"`
	About        pgtype.Text        `json:"about"`
	ContactEmail pgtype.Text        `json:"contact_email"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type UserProject struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ProjectName string             `json:"project_name"`
	Description string             `json:"description"`
	ProjectUrl  pgtype.Text        `json:"project_url"`
	Tags        []string           `json:"tags"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	IsAcademic  bool               `json:"is_academic"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type UserSkill struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	SkillName        string             `json:"skill_name"`
	ProficiencyLevel SkillLevel         `json:"proficiency_level"`
	Tags             []string           `json:"tags"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}
