// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryDeleteCertificacao = `-- name: QueryDeleteCertificacao :exec
DELETE FROM certificacoes WHERE id = $1
`

func (q *Queries) QueryDeleteCertificacao(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, queryDeleteCertificacao, id)
	return err
}

const queryDeleteCurriculoGerado = `-- name: QueryDeleteCurriculoGerado :exec
DELETE FROM curriculos_gerados WHERE id = $1
`

func (q *Queries) QueryDeleteCurriculoGerado(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, queryDeleteCurriculoGerado, id)
	return err
}

const queryDeleteExperiencia = `-- name: QueryDeleteExperiencia :exec
DELETE FROM experiencias WHERE id = $1
`

func (q *Queries) QueryDeleteExperiencia(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, queryDeleteExperiencia, id)
	return err
}

const queryDeleteFiltro = `-- name: QueryDeleteFiltro :exec
DELETE FROM filtros WHERE id = $1
`

func (q *Queries) QueryDeleteFiltro(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, queryDeleteFiltro, id)
	return err
}

const queryDeleteHabilidade = `-- name: QueryDeleteHabilidade :exec
DELETE FROM habilidades WHERE id = $1
`

func (q *Queries) QueryDeleteHabilidade(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, queryDeleteHabilidade, id)
	return err
}

const queryDeleteProjeto = `-- name: QueryDeleteProjeto :exec
DELETE FROM projetos WHERE id = $1
`

func (q *Queries) QueryDeleteProjeto(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, queryDeleteProjeto, id)
	return err
}

const queryDeleteVaga = `-- name: QueryDeleteVaga :exec
DELETE FROM vagas WHERE id = $1
`

func (q *Queries) QueryDeleteVaga(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, queryDeleteVaga, id)
	return err
}

const queryFindVagaByUrl = `-- name: QueryFindVagaByUrl :one
SELECT id FROM vagas WHERE url = $1
`

func (q *Queries) QueryFindVagaByUrl(ctx context.Context, url string) (int64, error) {
	row := q.db.QueryRow(ctx, queryFindVagaByUrl, url)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const queryFindVagasPendentes = `-- name: QueryFindVagasPendentes :many
SELECT id, url, empresa, titulo, descricao, stack, requisitos, status, criado_em, idioma FROM vagas where status = 'pendente'
`

func (q *Queries) QueryFindVagasPendentes(ctx context.Context) ([]Vaga, error) {
	rows, err := q.db.Query(ctx, queryFindVagasPendentes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vaga
	for rows.Next() {
		var i Vaga
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Empresa,
			&i.Titulo,
			&i.Descricao,
			&i.Stack,
			&i.Requisitos,
			&i.Status,
			&i.CriadoEm,
			&i.Idioma,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryFindVagasPendentesLimit = `-- name: QueryFindVagasPendentesLimit :many
SELECT id, url, empresa, titulo, descricao, stack, requisitos, status, criado_em, idioma FROM vagas where status = 'pendente' ORDER BY id LIMIT $1
`

func (q *Queries) QueryFindVagasPendentesLimit(ctx context.Context, limit int32) ([]Vaga, error) {
	rows, err := q.db.Query(ctx, queryFindVagasPendentesLimit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vaga
	for rows.Next() {
		var i Vaga
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Empresa,
			&i.Titulo,
			&i.Descricao,
			&i.Stack,
			&i.Requisitos,
			&i.Status,
			&i.CriadoEm,
			&i.Idioma,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryGetCurriculoComVaga = `-- name: QueryGetCurriculoComVaga :one
SELECT cg.id, cg.conteudo_json, cg.resume_path, cg.cover_letter_path,
       v.empresa, v.titulo, v.idioma
FROM curriculos_gerados cg
JOIN vagas v ON v.id = cg.vaga_id
WHERE cg.id = $1
`

type QueryGetCurriculoComVagaRow struct {
	ID              int64       `json:"id"`
	ConteudoJson    []byte      `json:"conteudo_json"`
	ResumePath      pgtype.Text `json:"resume_path"`
	CoverLetterPath pgtype.Text `json:"cover_letter_path"`
	Empresa         pgtype.Text `json:"empresa"`
	Titulo          pgtype.Text `json:"titulo"`
	Idioma          pgtype.Text `json:"idioma"`
}

func (q *Queries) QueryGetCurriculoComVaga(ctx context.Context, id int64) (QueryGetCurriculoComVagaRow, error) {
	row := q.db.QueryRow(ctx, queryGetCurriculoComVaga, id)
	var i QueryGetCurriculoComVagaRow
	err := row.Scan(
		&i.ID,
		&i.ConteudoJson,
		&i.ResumePath,
		&i.CoverLetterPath,
		&i.Empresa,
		&i.Titulo,
		&i.Idioma,
	)
	return i, err
}

const queryInsertAlert = `-- name: QueryInsertAlert :exec
INSERT INTO alerta (sensor_id, status) VALUES ($1, $2)
`

type QueryInsertAlertParams struct {
	SensorID int64        `json:"sensor_id"`
	Status   SensorStatus `json:"status"`
}

func (q *Queries) QueryInsertAlert(ctx context.Context, arg QueryInsertAlertParams) error {
	_, err := q.db.Exec(ctx, queryInsertAlert, arg.SensorID, arg.Status)
	return err
}

const queryInsertAlertHistory = `-- name: QueryInsertAlertHistory :exec
INSERT INTO historico (sensor_id, value) VALUES ($1, $2)
`

type QueryInsertAlertHistoryParams struct {
	SensorID int64   `json:"sensor_id"`
	Value    float64 `json:"value"`
}

func (q *Queries) QueryInsertAlertHistory(ctx context.Context, arg QueryInsertAlertHistoryParams) error {
	_, err := q.db.Exec(ctx, queryInsertAlertHistory, arg.SensorID, arg.Value)
	return err
}

const queryInsertCertificacao = `-- name: QueryInsertCertificacao :one
INSERT INTO certificacoes(nome, emissor, emitido_em, codigo, link, tags)
VALUES ($1, $2, $3, $4, $5, $6::TEXT[])
RETURNING id, nome, emissor, emitido_em, codigo, link, tags
`

type QueryInsertCertificacaoParams struct {
	Nome      string      `json:"nome"`
	Emissor   string      `json:"emissor"`
	EmitidoEm pgtype.Date `json:"emitido_em"`
	Codigo    pgtype.Text `json:"codigo"`
	Link      pgtype.Text `json:"link"`
	Column6   []string    `json:"column_6"`
}

func (q *Queries) QueryInsertCertificacao(ctx context.Context, arg QueryInsertCertificacaoParams) (Certificaco, error) {
	row := q.db.QueryRow(ctx, queryInsertCertificacao,
		arg.Nome,
		arg.Emissor,
		arg.EmitidoEm,
		arg.Codigo,
		arg.Link,
		arg.Column6,
	)
	var i Certificaco
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Emissor,
		&i.EmitidoEm,
		&i.Codigo,
		&i.Link,
		&i.Tags,
	)
	return i, err
}

const queryInsertCurriculoGerado = `-- name: QueryInsertCurriculoGerado :exec
INSERT INTO curriculos_gerados(vaga_id, conteudo_json) VALUES($1, $2::JSONB)
`

type QueryInsertCurriculoGeradoParams struct {
	VagaID          int64  `json:"vaga_id"`
	CurriculoGerado []byte `json:"curriculo_gerado"`
}

func (q *Queries) QueryInsertCurriculoGerado(ctx context.Context, arg QueryInsertCurriculoGeradoParams) error {
	_, err := q.db.Exec(ctx, queryInsertCurriculoGerado, arg.VagaID, arg.CurriculoGerado)
	return err
}

const queryInsertExperiencia = `-- name: QueryInsertExperiencia :one
INSERT INTO experiencias(empresa, cargo, descricao, atual, data_inicio, data_fim, stack, conquistas, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, empresa, cargo, descricao, atual, data_inicio, data_fim, stack, conquistas, tags
`

type QueryInsertExperienciaParams struct {
	Empresa    string      `json:"empresa"`
	Cargo      string      `json:"cargo"`
	Descricao  pgtype.Text `json:"descricao"`
	Atual      bool        `json:"atual"`
	DataInicio pgtype.Date `json:"data_inicio"`
	DataFim    pgtype.Date `json:"data_fim"`
	Stack      []string    `json:"stack"`
	Conquistas []string    `json:"conquistas"`
	Tags       []string    `json:"tags"`
}

func (q *Queries) QueryInsertExperiencia(ctx context.Context, arg QueryInsertExperienciaParams) (Experiencia, error) {
	row := q.db.QueryRow(ctx, queryInsertExperiencia,
		arg.Empresa,
		arg.Cargo,
		arg.Descricao,
		arg.Atual,
		arg.DataInicio,
		arg.DataFim,
		arg.Stack,
		arg.Conquistas,
		arg.Tags,
	)
	var i Experiencia
	err := row.Scan(
		&i.ID,
		&i.Empresa,
		&i.Cargo,
		&i.Descricao,
		&i.Atual,
		&i.DataInicio,
		&i.DataFim,
		&i.Stack,
		&i.Conquistas,
		&i.Tags,
	)
	return i, err
}

const queryInsertFeedback = `-- name: QueryInsertFeedback :exec
INSERT INTO feedback (curriculo_id, vaga_id, status, comentario)
VALUES ($1, $2, $3, $4)
`

type QueryInsertFeedbackParams struct {
	CurriculoID int64          `json:"curriculo_id"`
	VagaID      int64          `json:"vaga_id"`
	Status      StatusFeedback `json:"status"`
	Comentario  pgtype.Text    `json:"comentario"`
}

func (q *Queries) QueryInsertFeedback(ctx context.Context, arg QueryInsertFeedbackParams) error {
	_, err := q.db.Exec(ctx, queryInsertFeedback,
		arg.CurriculoID,
		arg.VagaID,
		arg.Status,
		arg.Comentario,
	)
	return err
}

const queryInsertFiltro = `-- name: QueryInsertFiltro :one
INSERT INTO filtros(keyword) VALUES ($1) RETURNING id, keyword
`

func (q *Queries) QueryInsertFiltro(ctx context.Context, keyword string) (Filtro, error) {
	row := q.db.QueryRow(ctx, queryInsertFiltro, keyword)
	var i Filtro
	err := row.Scan(&i.ID, &i.Keyword)
	return i, err
}

const queryInsertHabilidade = `-- name: QueryInsertHabilidade :one
INSERT INTO habilidades(nome, nivel, tags)
VALUES ($1, $2, $3::TEXT[])
RETURNING id, nome, nivel, tags
`

type QueryInsertHabilidadeParams struct {
	Nome    string          `json:"nome"`
	Nivel   NivelHabilidade `json:"nivel"`
	Column3 []string        `json:"column_3"`
}

func (q *Queries) QueryInsertHabilidade(ctx context.Context, arg QueryInsertHabilidadeParams) (Habilidade, error) {
	row := q.db.QueryRow(ctx, queryInsertHabilidade, arg.Nome, arg.Nivel, arg.Column3)
	var i Habilidade
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Nivel,
		&i.Tags,
	)
	return i, err
}

const queryInsertProjeto = `-- name: QueryInsertProjeto :one
INSERT INTO projetos(nome, descricao, link, tags, data_inicio, data_fim, facultativo)
VALUES ($1, $2, $3, $4::TEXT[], $5, $6, $7)
RETURNING id, nome, descricao, link, tags, data_inicio, data_fim, facultativo
`

type QueryInsertProjetoParams struct {
	Nome        string      `json:"nome"`
	Descricao   pgtype.Text `json:"descricao"`
	Link        pgtype.Text `json:"link"`
	Column4     []string    `json:"column_4"`
	DataInicio  pgtype.Date `json:"data_inicio"`
	DataFim     pgtype.Date `json:"data_fim"`
	Facultativo bool        `json:"facultativo"`
}

func (q *Queries) QueryInsertProjeto(ctx context.Context, arg QueryInsertProjetoParams) (Projeto, error) {
	row := q.db.QueryRow(ctx, queryInsertProjeto,
		arg.Nome,
		arg.Descricao,
		arg.Link,
		arg.Column4,
		arg.DataInicio,
		arg.DataFim,
		arg.Facultativo,
	)
	var i Projeto
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Descricao,
		&i.Link,
		&i.Tags,
		&i.DataInicio,
		&i.DataFim,
		&i.Facultativo,
	)
	return i, err
}

const queryInsertVaga = `-- name: QueryInsertVaga :exec
INSERT INTO vagas (url, titulo, descricao, empresa, stack, requisitos, idioma) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type QueryInsertVagaParams struct {
	Url        string      `json:"url"`
	Titulo     pgtype.Text `json:"titulo"`
	Descricao  pgtype.Text `json:"descricao"`
	Empresa    pgtype.Text `json:"empresa"`
	Stack      []string    `json:"stack"`
	Requisitos []string    `json:"requisitos"`
	Idioma     pgtype.Text `json:"idioma"`
}

func (q *Queries) QueryInsertVaga(ctx context.Context, arg QueryInsertVagaParams) error {
	_, err := q.db.Exec(ctx, queryInsertVaga,
		arg.Url,
		arg.Titulo,
		arg.Descricao,
		arg.Empresa,
		arg.Stack,
		arg.Requisitos,
		arg.Idioma,
	)
	return err
}

const queryListarCurriculos = `-- name: QueryListarCurriculos :many
SELECT cg.id, cg.vaga_id, cg.conteudo_json, cg.criado_em,
       v.empresa, v.titulo, v.url
FROM curriculos_gerados cg
JOIN vagas v ON v.id = cg.vaga_id
ORDER BY cg.criado_em DESC
LIMIT $1 OFFSET $2
`

type QueryListarCurriculosParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type QueryListarCurriculosRow struct {
	ID           int64            `json:"id"`
	VagaID       int64            `json:"vaga_id"`
	ConteudoJson []byte           `json:"conteudo_json"`
	CriadoEm     pgtype.Timestamp `json:"criado_em"`
	Empresa      pgtype.Text      `json:"empresa"`
	Titulo       pgtype.Text      `json:"titulo"`
	Url          string           `json:"url"`
}

func (q *Queries) QueryListarCurriculos(ctx context.Context, arg QueryListarCurriculosParams) ([]QueryListarCurriculosRow, error) {
	rows, err := q.db.Query(ctx, queryListarCurriculos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryListarCurriculosRow
	for rows.Next() {
		var i QueryListarCurriculosRow
		if err := rows.Scan(
			&i.ID,
			&i.VagaID,
			&i.ConteudoJson,
			&i.CriadoEm,
			&i.Empresa,
			&i.Titulo,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryListarVagas = `-- name: QueryListarVagas :many
SELECT id, url, empresa, titulo, descricao, stack, requisitos, status, criado_em, idioma FROM public.vagas WHERE ($1 = '' OR status::text = $1)
ORDER BY criado_em DESC LIMIT $3 OFFSET $2
`

type QueryListarVagasParams struct {
	Status  interface{} `json:"status"`
	Pagina  int32       `json:"pagina"`
	Tamanho int32       `json:"tamanho"`
}

func (q *Queries) QueryListarVagas(ctx context.Context, arg QueryListarVagasParams) ([]Vaga, error) {
	rows, err := q.db.Query(ctx, queryListarVagas, arg.Status, arg.Pagina, arg.Tamanho)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vaga
	for rows.Next() {
		var i Vaga
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Empresa,
			&i.Titulo,
			&i.Descricao,
			&i.Stack,
			&i.Requisitos,
			&i.Status,
			&i.CriadoEm,
			&i.Idioma,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectAllCertificacoes = `-- name: QuerySelectAllCertificacoes :many
SELECT id, nome, emissor, emitido_em, codigo, link, tags FROM certificacoes ORDER BY emitido_em DESC
`

func (q *Queries) QuerySelectAllCertificacoes(ctx context.Context) ([]Certificaco, error) {
	rows, err := q.db.Query(ctx, querySelectAllCertificacoes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificaco
	for rows.Next() {
		var i Certificaco
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Emissor,
			&i.EmitidoEm,
			&i.Codigo,
			&i.Link,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectAllExperiencias = `-- name: QuerySelectAllExperiencias :many
SELECT id, empresa, cargo, descricao, atual, data_inicio, data_fim, stack, conquistas, tags FROM experiencias ORDER BY data_inicio DESC
`

func (q *Queries) QuerySelectAllExperiencias(ctx context.Context) ([]Experiencia, error) {
	rows, err := q.db.Query(ctx, querySelectAllExperiencias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Experiencia
	for rows.Next() {
		var i Experiencia
		if err := rows.Scan(
			&i.ID,
			&i.Empresa,
			&i.Cargo,
			&i.Descricao,
			&i.Atual,
			&i.DataInicio,
			&i.DataFim,
			&i.Stack,
			&i.Conquistas,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectAllFiltros = `-- name: QuerySelectAllFiltros :many
SELECT keyword FROM filtros
`

func (q *Queries) QuerySelectAllFiltros(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, querySelectAllFiltros)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var keyword string
		if err := rows.Scan(&keyword); err != nil {
			return nil, err
		}
		items = append(items, keyword)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectAllFiltrosWithID = `-- name: QuerySelectAllFiltrosWithID :many
SELECT id, keyword FROM filtros ORDER BY keyword
`

func (q *Queries) QuerySelectAllFiltrosWithID(ctx context.Context) ([]Filtro, error) {
	rows, err := q.db.Query(ctx, querySelectAllFiltrosWithID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Filtro
	for rows.Next() {
		var i Filtro
		if err := rows.Scan(&i.ID, &i.Keyword); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectAllFormacoes = `-- name: QuerySelectAllFormacoes :many
SELECT id, instituicao, curso, data_inicio, data_fim, descricao FROM formacao ORDER BY data_inicio DESC
`

func (q *Queries) QuerySelectAllFormacoes(ctx context.Context) ([]Formacao, error) {
	rows, err := q.db.Query(ctx, querySelectAllFormacoes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Formacao
	for rows.Next() {
		var i Formacao
		if err := rows.Scan(
			&i.ID,
			&i.Instituicao,
			&i.Curso,
			&i.DataInicio,
			&i.DataFim,
			&i.Descricao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectAllHabilidades = `-- name: QuerySelectAllHabilidades :many
SELECT id, nome, nivel, tags FROM habilidades ORDER BY nome
`

func (q *Queries) QuerySelectAllHabilidades(ctx context.Context) ([]Habilidade, error) {
	rows, err := q.db.Query(ctx, querySelectAllHabilidades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habilidade
	for rows.Next() {
		var i Habilidade
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Nivel,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectAllProjetos = `-- name: QuerySelectAllProjetos :many
SELECT id, nome, descricao, link, tags, data_inicio, data_fim, facultativo FROM projetos ORDER BY data_inicio DESC
`

func (q *Queries) QuerySelectAllProjetos(ctx context.Context) ([]Projeto, error) {
	rows, err := q.db.Query(ctx, querySelectAllProjetos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Projeto
	for rows.Next() {
		var i Projeto
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Descricao,
			&i.Link,
			&i.Tags,
			&i.DataInicio,
			&i.DataFim,
			&i.Facultativo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectBasicInfo = `-- name: QuerySelectBasicInfo :one
select id, nome, email, telefone, linkedin, github, portfolio, resumo, criado_em from public.informacoes_basicas order by criado_em desc limit 1
`

func (q *Queries) QuerySelectBasicInfo(ctx context.Context) (InformacoesBasica, error) {
	row := q.db.QueryRow(ctx, querySelectBasicInfo)
	var i InformacoesBasica
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Telefone,
		&i.Linkedin,
		&i.Github,
		&i.Portfolio,
		&i.Resumo,
		&i.CriadoEm,
	)
	return i, err
}

const querySelectCurriculoExcelente = `-- name: QuerySelectCurriculoExcelente :many
SELECT cg.conteudo_json FROM feedback f
JOIN curriculos_gerados cg ON cg.id = f.curriculo_id
WHERE f.status = 'excelente'
ORDER BY f.criado_em DESC
LIMIT 3
`

func (q *Queries) QuerySelectCurriculoExcelente(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, querySelectCurriculoExcelente)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var conteudo_json []byte
		if err := rows.Scan(&conteudo_json); err != nil {
			return nil, err
		}
		items = append(items, conteudo_json)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectExperienciasByTags = `-- name: QuerySelectExperienciasByTags :many
SELECT id, empresa, cargo, descricao, atual, data_inicio, data_fim, stack, conquistas, tags FROM experiencias WHERE tags && $1::TEXT[] ORDER BY data_inicio DESC
`

func (q *Queries) QuerySelectExperienciasByTags(ctx context.Context, dollar_1 []string) ([]Experiencia, error) {
	rows, err := q.db.Query(ctx, querySelectExperienciasByTags, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Experiencia
	for rows.Next() {
		var i Experiencia
		if err := rows.Scan(
			&i.ID,
			&i.Empresa,
			&i.Cargo,
			&i.Descricao,
			&i.Atual,
			&i.DataInicio,
			&i.DataFim,
			&i.Stack,
			&i.Conquistas,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectFeedbackMidGood = `-- name: QuerySelectFeedbackMidGood :many
SELECT comentario FROM feedback 
WHERE status IN ('medio', 'bom') 
AND comentario IS NOT NULL
ORDER BY criado_em DESC 
LIMIT 5
`

func (q *Queries) QuerySelectFeedbackMidGood(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, querySelectFeedbackMidGood)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var comentario pgtype.Text
		if err := rows.Scan(&comentario); err != nil {
			return nil, err
		}
		items = append(items, comentario)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectHabilidadesByTags = `-- name: QuerySelectHabilidadesByTags :many
SELECT id, nome, nivel, tags FROM habilidades WHERE tags && $1::TEXT[]
`

func (q *Queries) QuerySelectHabilidadesByTags(ctx context.Context, dollar_1 []string) ([]Habilidade, error) {
	rows, err := q.db.Query(ctx, querySelectHabilidadesByTags, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habilidade
	for rows.Next() {
		var i Habilidade
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Nivel,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectProjetosByTags = `-- name: QuerySelectProjetosByTags :many
SELECT id, nome, descricao, link, tags, data_inicio, data_fim, facultativo FROM projetos WHERE tags && $1::TEXT[]
`

func (q *Queries) QuerySelectProjetosByTags(ctx context.Context, dollar_1 []string) ([]Projeto, error) {
	rows, err := q.db.Query(ctx, querySelectProjetosByTags, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Projeto
	for rows.Next() {
		var i Projeto
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Descricao,
			&i.Link,
			&i.Tags,
			&i.DataInicio,
			&i.DataFim,
			&i.Facultativo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryUpdateCurriculoPaths = `-- name: QueryUpdateCurriculoPaths :exec
UPDATE curriculos_gerados
SET resume_path = $2, cover_letter_path = $3
WHERE id = $1
`

type QueryUpdateCurriculoPathsParams struct {
	ID              int64       `json:"id"`
	ResumePath      pgtype.Text `json:"resume_path"`
	CoverLetterPath pgtype.Text `json:"cover_letter_path"`
}

func (q *Queries) QueryUpdateCurriculoPaths(ctx context.Context, arg QueryUpdateCurriculoPathsParams) error {
	_, err := q.db.Exec(ctx, queryUpdateCurriculoPaths, arg.ID, arg.ResumePath, arg.CoverLetterPath)
	return err
}

const queryUpdateSensorStatus = `-- name: QueryUpdateSensorStatus :exec
UPDATE sensores SET status = $1 WHERE id = $2
`

type QueryUpdateSensorStatusParams struct {
	Status SensorStatus `json:"status"`
	ID     int64        `json:"id"`
}

func (q *Queries) QueryUpdateSensorStatus(ctx context.Context, arg QueryUpdateSensorStatusParams) error {
	_, err := q.db.Exec(ctx, queryUpdateSensorStatus, arg.Status, arg.ID)
	return err
}

const queryUpdateVagaStatus = `-- name: QueryUpdateVagaStatus :exec
UPDATE vagas SET 
    status = $2,
    empresa = $3,
    titulo = $4,
    stack = $5, 
    requisitos = $6,
    descricao = $7
WHERE id = $1
`

type QueryUpdateVagaStatusParams struct {
	ID         int64       `json:"id"`
	Status     StatusVaga  `json:"status"`
	Empresa    pgtype.Text `json:"empresa"`
	Titulo     pgtype.Text `json:"titulo"`
	Stack      []string    `json:"stack"`
	Requisitos []string    `json:"requisitos"`
	Descricao  pgtype.Text `json:"descricao"`
}

func (q *Queries) QueryUpdateVagaStatus(ctx context.Context, arg QueryUpdateVagaStatusParams) error {
	_, err := q.db.Exec(ctx, queryUpdateVagaStatus,
		arg.ID,
		arg.Status,
		arg.Empresa,
		arg.Titulo,
		arg.Stack,
		arg.Requisitos,
		arg.Descricao,
	)
	return err
}

const queryUpdateVagaStatusOnly = `-- name: QueryUpdateVagaStatusOnly :exec
UPDATE vagas SET status = $2 WHERE id = $1
`

type QueryUpdateVagaStatusOnlyParams struct {
	ID     int64      `json:"id"`
	Status StatusVaga `json:"status"`
}

func (q *Queries) QueryUpdateVagaStatusOnly(ctx context.Context, arg QueryUpdateVagaStatusOnlyParams) error {
	_, err := q.db.Exec(ctx, queryUpdateVagaStatusOnly, arg.ID, arg.Status)
	return err
}

const queryUpdateVagaStatusToProcessando = `-- name: QueryUpdateVagaStatusToProcessando :exec
UPDATE vagas SET status = 'processando' WHERE id = $1
`

func (q *Queries) QueryUpdateVagaStatusToProcessando(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, queryUpdateVagaStatusToProcessando, id)
	return err
}

const queryUpsertInformacoesBasicas = `-- name: QueryUpsertInformacoesBasicas :one
INSERT INTO informacoes_basicas(id, nome, email, telefone, linkedin, github, portfolio, resumo)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    nome      = EXCLUDED.nome,
    email     = EXCLUDED.email,
    telefone  = EXCLUDED.telefone,
    linkedin  = EXCLUDED.linkedin,
    github    = EXCLUDED.github,
    portfolio = EXCLUDED.portfolio,
    resumo    = EXCLUDED.resumo
RETURNING id, nome, email, telefone, linkedin, github, portfolio, resumo, criado_em
`

type QueryUpsertInformacoesBasicasParams struct {
	ID        int64       `json:"id"`
	Nome      string      `json:"nome"`
	Email     string      `json:"email"`
	Telefone  pgtype.Text `json:"telefone"`
	Linkedin  pgtype.Text `json:"linkedin"`
	Github    pgtype.Text `json:"github"`
	Portfolio pgtype.Text `json:"portfolio"`
	Resumo    pgtype.Text `json:"resumo"`
}

func (q *Queries) QueryUpsertInformacoesBasicas(ctx context.Context, arg QueryUpsertInformacoesBasicasParams) (InformacoesBasica, error) {
	row := q.db.QueryRow(ctx, queryUpsertInformacoesBasicas,
		arg.ID,
		arg.Nome,
		arg.Email,
		arg.Telefone,
		arg.Linkedin,
		arg.Github,
		arg.Portfolio,
		arg.Resumo,
	)
	var i InformacoesBasica
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Telefone,
		&i.Linkedin,
		&i.Github,
		&i.Portfolio,
		&i.Resumo,
		&i.CriadoEm,
	)
	return i, err
}
