// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const test = `-- name: Test :exec
SELECT now()
`

func (q *Queries) Test(ctx context.Context) error {
	_, err := q.db.Exec(ctx, test)
	return err
}
