// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: security.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryInsertSecurityEvent = `-- name: QueryInsertSecurityEvent :exec
INSERT INTO security_events (event_type, ip, user_id, metadata)
VALUES ($1, $2, $3, $4)
`

type QueryInsertSecurityEventParams struct {
	EventType SecurityEventType `json:"event_type"`
	Ip        pgtype.Text `json:"ip"`
	UserID    pgtype.UUID `json:"user_id"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) QueryInsertSecurityEvent(ctx context.Context, arg QueryInsertSecurityEventParams) error {
	_, err := q.db.Exec(ctx, queryInsertSecurityEvent,
		arg.EventType,
		arg.Ip,
		arg.UserID,
		arg.Metadata,
	)
	return err
}

const queryListSecurityEvents = `-- name: QueryListSecurityEvents :many
SELECT id, event_type, ip, user_id, metadata, created_at
FROM security_events
WHERE created_at >= $1
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) QueryListSecurityEvents(ctx context.Context, createdAt pgtype.Timestamptz) ([]SecurityEvent, error) {
	rows, err := q.db.Query(ctx, queryListSecurityEvents, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecurityEvent
	for rows.Next() {
		var i SecurityEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Ip,
			&i.UserID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
