// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryDeleteAcademicHistory = `-- name: QueryDeleteAcademicHistory :exec
UPDATE user_academic_histories
SET deleted_at = now()
WHERE id = $1 AND user_id = $2
`

type QueryDeleteAcademicHistoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryDeleteAcademicHistory(ctx context.Context, arg QueryDeleteAcademicHistoryParams) error {
	_, err := q.db.Exec(ctx, queryDeleteAcademicHistory, arg.ID, arg.UserID)
	return err
}

const queryDeleteCertificate = `-- name: QueryDeleteCertificate :exec
UPDATE user_certificates
SET deleted_at = now()
WHERE id = $1 AND user_id = $2
`

type QueryDeleteCertificateParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryDeleteCertificate(ctx context.Context, arg QueryDeleteCertificateParams) error {
	_, err := q.db.Exec(ctx, queryDeleteCertificate, arg.ID, arg.UserID)
	return err
}

const queryDeleteExperience = `-- name: QueryDeleteExperience :exec
UPDATE user_experiences
SET deleted_at = now()
WHERE id = $1 AND user_id = $2
`

type QueryDeleteExperienceParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryDeleteExperience(ctx context.Context, arg QueryDeleteExperienceParams) error {
	_, err := q.db.Exec(ctx, queryDeleteExperience, arg.ID, arg.UserID)
	return err
}

const queryDeleteProject = `-- name: QueryDeleteProject :exec
UPDATE user_projects
SET deleted_at = now()
WHERE id = $1 AND user_id = $2
`

type QueryDeleteProjectParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryDeleteProject(ctx context.Context, arg QueryDeleteProjectParams) error {
	_, err := q.db.Exec(ctx, queryDeleteProject, arg.ID, arg.UserID)
	return err
}

const queryDeleteSkill = `-- name: QueryDeleteSkill :exec
UPDATE user_skills
SET deleted_at = now()
WHERE id = $1 AND user_id = $2
`

type QueryDeleteSkillParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryDeleteSkill(ctx context.Context, arg QueryDeleteSkillParams) error {
	_, err := q.db.Exec(ctx, queryDeleteSkill, arg.ID, arg.UserID)
	return err
}

const queryInsertAcademicHistory = `-- name: QueryInsertAcademicHistory :one
INSERT INTO user_academic_histories(
    user_id, institution_name, course_name, start_date, end_date, description
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, institution_name, course_name, start_date, end_date, description, created_at, updated_at, deleted_at
`

type QueryInsertAcademicHistoryParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	InstitutionName string      `json:"institution_name"`
	CourseName      string      `json:"course_name"`
	StartDate       pgtype.Date `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
	Description     pgtype.Text `json:"description"`
}

func (q *Queries) QueryInsertAcademicHistory(ctx context.Context, arg QueryInsertAcademicHistoryParams) (UserAcademicHistory, error) {
	row := q.db.QueryRow(ctx, queryInsertAcademicHistory,
		arg.UserID,
		arg.InstitutionName,
		arg.CourseName,
		arg.StartDate,
		arg.EndDate,
		arg.Description,
	)
	var i UserAcademicHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstitutionName,
		&i.CourseName,
		&i.StartDate,
		&i.EndDate,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryInsertAccount = `-- name: QueryInsertAccount :one
INSERT INTO user_accounts(email, password_hash)
VALUES ($1, $2)
RETURNING id, email, created_at
`

type QueryInsertAccountParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type QueryInsertAccountRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) QueryInsertAccount(ctx context.Context, arg QueryInsertAccountParams) (QueryInsertAccountRow, error) {
	row := q.db.QueryRow(ctx, queryInsertAccount, arg.Email, arg.PasswordHash)
	var i QueryInsertAccountRow
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const queryInsertCertificate = `-- name: QueryInsertCertificate :one
INSERT INTO user_certificates(
    user_id, certificate_name, issuing_organization, issue_date, credential_url, tags
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, certificate_name, issuing_organization, issue_date, credential_url, tags, created_at, updated_at, deleted_at
`

type QueryInsertCertificateParams struct {
	UserID              pgtype.UUID `json:"user_id"`
	CertificateName     string      `json:"certificate_name"`
	IssuingOrganization string      `json:"issuing_organization"`
	IssueDate           pgtype.Date `json:"issue_date"`
	CredentialUrl       pgtype.Text `json:"credential_url"`
	Tags                []string    `json:"tags"`
}

func (q *Queries) QueryInsertCertificate(ctx context.Context, arg QueryInsertCertificateParams) (UserCertificate, error) {
	row := q.db.QueryRow(ctx, queryInsertCertificate,
		arg.UserID,
		arg.CertificateName,
		arg.IssuingOrganization,
		arg.IssueDate,
		arg.CredentialUrl,
		arg.Tags,
	)
	var i UserCertificate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CertificateName,
		&i.IssuingOrganization,
		&i.IssueDate,
		&i.CredentialUrl,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryInsertExperience = `-- name: QueryInsertExperience :one
INSERT INTO user_experiences(
    user_id, company_name, job_role, description,
    is_current_job, start_date, end_date, tech_stack, achievements, tags
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9, $10
) RETURNING id, user_id, company_name, job_role, description, is_current_job, start_date, end_date, tech_stack, achievements, tags, created_at, updated_at, deleted_at
`

type QueryInsertExperienceParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CompanyName  string      `json:"company_name"`
	JobRole      string      `json:"job_role"`
	Description  pgtype.Text `json:"description"`
	IsCurrentJob bool        `json:"is_current_job"`
	StartDate    pgtype.Date `json:"start_date"`
	EndDate      pgtype.Date `json:"end_date"`
	TechStack    []string    `json:"tech_stack"`
	Achievements []string    `json:"achievements"`
	Tags         []string    `json:"tags"`
}

func (q *Queries) QueryInsertExperience(ctx context.Context, arg QueryInsertExperienceParams) (UserExperience, error) {
	row := q.db.QueryRow(ctx, queryInsertExperience,
		arg.UserID,
		arg.CompanyName,
		arg.JobRole,
		arg.Description,
		arg.IsCurrentJob,
		arg.StartDate,
		arg.EndDate,
		arg.TechStack,
		arg.Achievements,
		arg.Tags,
	)
	var i UserExperience
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.JobRole,
		&i.Description,
		&i.IsCurrentJob,
		&i.StartDate,
		&i.EndDate,
		&i.TechStack,
		&i.Achievements,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryInsertProject = `-- name: QueryInsertProject :one
INSERT INTO user_projects(
    user_id, project_name, description, project_url,
    tags, start_date, end_date, is_academic
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
) RETURNING id, user_id, project_name, description, project_url, tags, start_date, end_date, is_academic, created_at, updated_at, deleted_at
`

type QueryInsertProjectParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ProjectName string      `json:"project_name"`
	Description string      `json:"description"`
	ProjectUrl  pgtype.Text `json:"project_url"`
	Tags        []string    `json:"tags"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	IsAcademic  bool        `json:"is_academic"`
}

func (q *Queries) QueryInsertProject(ctx context.Context, arg QueryInsertProjectParams) (UserProject, error) {
	row := q.db.QueryRow(ctx, queryInsertProject,
		arg.UserID,
		arg.ProjectName,
		arg.Description,
		arg.ProjectUrl,
		arg.Tags,
		arg.StartDate,
		arg.EndDate,
		arg.IsAcademic,
	)
	var i UserProject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectName,
		&i.Description,
		&i.ProjectUrl,
		&i.Tags,
		&i.StartDate,
		&i.EndDate,
		&i.IsAcademic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryInsertSkill = `-- name: QueryInsertSkill :one
INSERT INTO user_skills(user_id, skill_name, proficiency_level, tags)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, skill_name, proficiency_level, tags, created_at, updated_at, deleted_at
`

type QueryInsertSkillParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	SkillName        string      `json:"skill_name"`
	ProficiencyLevel SkillLevel  `json:"proficiency_level"`
	Tags             []string    `json:"tags"`
}

func (q *Queries) QueryInsertSkill(ctx context.Context, arg QueryInsertSkillParams) (UserSkill, error) {
	row := q.db.QueryRow(ctx, queryInsertSkill,
		arg.UserID,
		arg.SkillName,
		arg.ProficiencyLevel,
		arg.Tags,
	)
	var i UserSkill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SkillName,
		&i.ProficiencyLevel,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const querySelectAccountByEmail = `-- name: QuerySelectAccountByEmail :one
SELECT id, email, password_hash, deleted_at FROM user_accounts
WHERE email = $1 AND deleted_at IS NULL
`

type QuerySelectAccountByEmailRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) QuerySelectAccountByEmail(ctx context.Context, email string) (QuerySelectAccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, querySelectAccountByEmail, email)
	var i QuerySelectAccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DeletedAt,
	)
	return i, err
}

const querySelectAllAcademicHistories = `-- name: QuerySelectAllAcademicHistories :many
SELECT id, user_id, institution_name, course_name, start_date, end_date, description, created_at, updated_at, deleted_at FROM user_academic_histories
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY start_date DESC
`

func (q *Queries) QuerySelectAllAcademicHistories(ctx context.Context, userID pgtype.UUID) ([]UserAcademicHistory, error) {
	rows, err := q.db.Query(ctx, querySelectAllAcademicHistories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAcademicHistory
	for rows.Next() {
		var i UserAcademicHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstitutionName,
			&i.CourseName,
			&i.StartDate,
			&i.EndDate,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectAllCertificates = `-- name: QuerySelectAllCertificates :many
SELECT id, user_id, certificate_name, issuing_organization, issue_date, credential_url, tags, created_at, updated_at, deleted_at FROM user_certificates
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY issue_date DESC
`

func (q *Queries) QuerySelectAllCertificates(ctx context.Context, userID pgtype.UUID) ([]UserCertificate, error) {
	rows, err := q.db.Query(ctx, querySelectAllCertificates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCertificate
	for rows.Next() {
		var i UserCertificate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CertificateName,
			&i.IssuingOrganization,
			&i.IssueDate,
			&i.CredentialUrl,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectAllExperiences = `-- name: QuerySelectAllExperiences :many
SELECT id, user_id, company_name, job_role, description, is_current_job, start_date, end_date, tech_stack, achievements, tags, created_at, updated_at, deleted_at FROM user_experiences
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY start_date DESC
`

func (q *Queries) QuerySelectAllExperiences(ctx context.Context, userID pgtype.UUID) ([]UserExperience, error) {
	rows, err := q.db.Query(ctx, querySelectAllExperiences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserExperience
	for rows.Next() {
		var i UserExperience
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyName,
			&i.JobRole,
			&i.Description,
			&i.IsCurrentJob,
			&i.StartDate,
			&i.EndDate,
			&i.TechStack,
			&i.Achievements,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectAllProjects = `-- name: QuerySelectAllProjects :many
SELECT id, user_id, project_name, description, project_url, tags, start_date, end_date, is_academic, created_at, updated_at, deleted_at FROM user_projects
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY start_date DESC
`

func (q *Queries) QuerySelectAllProjects(ctx context.Context, userID pgtype.UUID) ([]UserProject, error) {
	rows, err := q.db.Query(ctx, querySelectAllProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserProject
	for rows.Next() {
		var i UserProject
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectName,
			&i.Description,
			&i.ProjectUrl,
			&i.Tags,
			&i.StartDate,
			&i.EndDate,
			&i.IsAcademic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectAllSkills = `-- name: QuerySelectAllSkills :many
SELECT id, user_id, skill_name, proficiency_level, tags, created_at, updated_at, deleted_at FROM user_skills
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY skill_name
`

func (q *Queries) QuerySelectAllSkills(ctx context.Context, userID pgtype.UUID) ([]UserSkill, error) {
	rows, err := q.db.Query(ctx, querySelectAllSkills, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSkill
	for rows.Next() {
		var i UserSkill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SkillName,
			&i.ProficiencyLevel,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectExperiencesByTags = `-- name: QuerySelectExperiencesByTags :many
SELECT id, user_id, company_name, job_role, description, is_current_job, start_date, end_date, tech_stack, achievements, tags, created_at, updated_at, deleted_at FROM user_experiences
WHERE user_id = $1 AND tags && $2::TEXT[] AND deleted_at IS NULL
ORDER BY start_date DESC
`

type QuerySelectExperiencesByTagsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Tags   []string    `json:"tags"`
}

func (q *Queries) QuerySelectExperiencesByTags(ctx context.Context, arg QuerySelectExperiencesByTagsParams) ([]UserExperience, error) {
	rows, err := q.db.Query(ctx, querySelectExperiencesByTags, arg.UserID, arg.Tags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserExperience
	for rows.Next() {
		var i UserExperience
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyName,
			&i.JobRole,
			&i.Description,
			&i.IsCurrentJob,
			&i.StartDate,
			&i.EndDate,
			&i.TechStack,
			&i.Achievements,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectProfile = `-- name: QuerySelectProfile :one
SELECT
    acc.email,
    p.full_name, p.phone, p.about, p.contact_email,
    l.linkedin_url, l.github_url, l.portfolio_url, l.other_links
FROM user_accounts acc
LEFT JOIN user_profiles p ON p.user_id = acc.id
LEFT JOIN user_links l ON l.user_id = acc.id
WHERE acc.id = $1 AND acc.deleted_at IS NULL
`

type QuerySelectProfileRow struct {
	Email        string      `json:"email"`
	FullName     pgtype.Text `json:"full_name"`
	Phone        pgtype.Text `json:"phone"`
	About        pgtype.Text `json:"about"`
	ContactEmail pgtype.Text `json:"contact_email"`
	LinkedinUrl  pgtype.Text `json:"linkedin_url"`
	GithubUrl    pgtype.Text `json:"github_url"`
	PortfolioUrl pgtype.Text `json:"portfolio_url"`
	OtherLinks   []byte      `json:"other_links"`
}

func (q *Queries) QuerySelectProfile(ctx context.Context, userID pgtype.UUID) (QuerySelectProfileRow, error) {
	row := q.db.QueryRow(ctx, querySelectProfile, userID)
	var i QuerySelectProfileRow
	err := row.Scan(
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.About,
		&i.ContactEmail,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.PortfolioUrl,
		&i.OtherLinks,
	)
	return i, err
}

const querySelectProjectsByTags = `-- name: QuerySelectProjectsByTags :many
SELECT id, user_id, project_name, description, project_url, tags, start_date, end_date, is_academic, created_at, updated_at, deleted_at FROM user_projects
WHERE user_id = $1 AND tags && $2::TEXT[] AND deleted_at IS NULL
`

type QuerySelectProjectsByTagsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Tags   []string    `json:"tags"`
}

func (q *Queries) QuerySelectProjectsByTags(ctx context.Context, arg QuerySelectProjectsByTagsParams) ([]UserProject, error) {
	rows, err := q.db.Query(ctx, querySelectProjectsByTags, arg.UserID, arg.Tags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserProject
	for rows.Next() {
		var i UserProject
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectName,
			&i.Description,
			&i.ProjectUrl,
			&i.Tags,
			&i.StartDate,
			&i.EndDate,
			&i.IsAcademic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySelectSkillsByTags = `-- name: QuerySelectSkillsByTags :many
SELECT id, user_id, skill_name, proficiency_level, tags, created_at, updated_at, deleted_at FROM user_skills
WHERE user_id = $1 AND tags && $2::TEXT[] AND deleted_at IS NULL
`

type QuerySelectSkillsByTagsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Tags   []string    `json:"tags"`
}

func (q *Queries) QuerySelectSkillsByTags(ctx context.Context, arg QuerySelectSkillsByTagsParams) ([]UserSkill, error) {
	rows, err := q.db.Query(ctx, querySelectSkillsByTags, arg.UserID, arg.Tags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSkill
	for rows.Next() {
		var i UserSkill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SkillName,
			&i.ProficiencyLevel,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const querySoftDeleteAccount = `-- name: QuerySoftDeleteAccount :exec
UPDATE user_accounts
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) QuerySoftDeleteAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, querySoftDeleteAccount, id)
	return err
}

const queryUpdateAcademicHistory = `-- name: QueryUpdateAcademicHistory :exec
UPDATE user_academic_histories
SET
    institution_name = $1,
    course_name      = $2,
    start_date       = $3,
    end_date         = $4,
    description      = $5,
    updated_at       = now()
WHERE id = $6 AND user_id = $7
`

type QueryUpdateAcademicHistoryParams struct {
	InstitutionName string      `json:"institution_name"`
	CourseName      string      `json:"course_name"`
	StartDate       pgtype.Date `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
	Description     pgtype.Text `json:"description"`
	ID              pgtype.UUID `json:"id"`
	UserID          pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryUpdateAcademicHistory(ctx context.Context, arg QueryUpdateAcademicHistoryParams) error {
	_, err := q.db.Exec(ctx, queryUpdateAcademicHistory,
		arg.InstitutionName,
		arg.CourseName,
		arg.StartDate,
		arg.EndDate,
		arg.Description,
		arg.ID,
		arg.UserID,
	)
	return err
}

const queryUpdateCertificate = `-- name: QueryUpdateCertificate :exec
UPDATE user_certificates
SET
    certificate_name     = $1,
    issuing_organization = $2,
    issue_date           = $3,
    credential_url       = $4,
    tags                 = $5,
    updated_at           = now()
WHERE id = $6 AND user_id = $7
`

type QueryUpdateCertificateParams struct {
	CertificateName     string      `json:"certificate_name"`
	IssuingOrganization string      `json:"issuing_organization"`
	IssueDate           pgtype.Date `json:"issue_date"`
	CredentialUrl       pgtype.Text `json:"credential_url"`
	Tags                []string    `json:"tags"`
	ID                  pgtype.UUID `json:"id"`
	UserID              pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryUpdateCertificate(ctx context.Context, arg QueryUpdateCertificateParams) error {
	_, err := q.db.Exec(ctx, queryUpdateCertificate,
		arg.CertificateName,
		arg.IssuingOrganization,
		arg.IssueDate,
		arg.CredentialUrl,
		arg.Tags,
		arg.ID,
		arg.UserID,
	)
	return err
}

const queryUpdateExperience = `-- name: QueryUpdateExperience :exec
UPDATE user_experiences
SET
    company_name   = $1,
    job_role       = $2,
    description    = $3,
    is_current_job = $4,
    start_date     = $5,
    end_date       = $6,
    tech_stack     = $7,
    achievements   = $8,
    tags           = $9,
    updated_at     = now()
WHERE id = $10 AND user_id = $11
`

type QueryUpdateExperienceParams struct {
	CompanyName  string      `json:"company_name"`
	JobRole      string      `json:"job_role"`
	Description  pgtype.Text `json:"description"`
	IsCurrentJob bool        `json:"is_current_job"`
	StartDate    pgtype.Date `json:"start_date"`
	EndDate      pgtype.Date `json:"end_date"`
	TechStack    []string    `json:"tech_stack"`
	Achievements []string    `json:"achievements"`
	Tags         []string    `json:"tags"`
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryUpdateExperience(ctx context.Context, arg QueryUpdateExperienceParams) error {
	_, err := q.db.Exec(ctx, queryUpdateExperience,
		arg.CompanyName,
		arg.JobRole,
		arg.Description,
		arg.IsCurrentJob,
		arg.StartDate,
		arg.EndDate,
		arg.TechStack,
		arg.Achievements,
		arg.Tags,
		arg.ID,
		arg.UserID,
	)
	return err
}

const queryUpdateProject = `-- name: QueryUpdateProject :exec
UPDATE user_projects
SET
    project_name = $1,
    description  = $2,
    project_url  = $3,
    tags         = $4,
    start_date   = $5,
    end_date     = $6,
    is_academic  = $7,
    updated_at   = now()
WHERE id = $8 AND user_id = $9
`

type QueryUpdateProjectParams struct {
	ProjectName string      `json:"project_name"`
	Description string      `json:"description"`
	ProjectUrl  pgtype.Text `json:"project_url"`
	Tags        []string    `json:"tags"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	IsAcademic  bool        `json:"is_academic"`
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryUpdateProject(ctx context.Context, arg QueryUpdateProjectParams) error {
	_, err := q.db.Exec(ctx, queryUpdateProject,
		arg.ProjectName,
		arg.Description,
		arg.ProjectUrl,
		arg.Tags,
		arg.StartDate,
		arg.EndDate,
		arg.IsAcademic,
		arg.ID,
		arg.UserID,
	)
	return err
}

const queryUpdateSkill = `-- name: QueryUpdateSkill :exec
UPDATE user_skills
SET
    skill_name        = $1,
    proficiency_level = $2,
    tags              = $3,
    updated_at        = now()
WHERE id = $4 AND user_id = $5
`

type QueryUpdateSkillParams struct {
	SkillName        string      `json:"skill_name"`
	ProficiencyLevel SkillLevel  `json:"proficiency_level"`
	Tags             []string    `json:"tags"`
	ID               pgtype.UUID `json:"id"`
	UserID           pgtype.UUID `json:"user_id"`
}

func (q *Queries) QueryUpdateSkill(ctx context.Context, arg QueryUpdateSkillParams) error {
	_, err := q.db.Exec(ctx, queryUpdateSkill,
		arg.SkillName,
		arg.ProficiencyLevel,
		arg.Tags,
		arg.ID,
		arg.UserID,
	)
	return err
}

const queryUpsertLinks = `-- name: QueryUpsertLinks :one
INSERT INTO user_links(user_id, linkedin_url, github_url, portfolio_url, other_links)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    linkedin_url  = EXCLUDED.linkedin_url,
    github_url    = EXCLUDED.github_url,
    portfolio_url = EXCLUDED.portfolio_url,
    other_links   = EXCLUDED.other_links,
    updated_at    = now()
RETURNING user_id, linkedin_url, github_url, portfolio_url, other_links, created_at, updated_at, deleted_at
`

type QueryUpsertLinksParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	LinkedinUrl  pgtype.Text `json:"linkedin_url"`
	GithubUrl    pgtype.Text `json:"github_url"`
	PortfolioUrl pgtype.Text `json:"portfolio_url"`
	OtherLinks   []byte      `json:"other_links"`
}

func (q *Queries) QueryUpsertLinks(ctx context.Context, arg QueryUpsertLinksParams) (UserLink, error) {
	row := q.db.QueryRow(ctx, queryUpsertLinks,
		arg.UserID,
		arg.LinkedinUrl,
		arg.GithubUrl,
		arg.PortfolioUrl,
		arg.OtherLinks,
	)
	var i UserLink
	err := row.Scan(
		&i.UserID,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.PortfolioUrl,
		&i.OtherLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpsertProfile = `-- name: QueryUpsertProfile :one
INSERT INTO user_profiles(user_id, full_name, phone, about, contact_email)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    full_name     = EXCLUDED.full_name,
    phone         = EXCLUDED.phone,
    about         = EXCLUDED.about,
    contact_email = EXCLUDED.contact_email,
    updated_at    = now()
RETURNING user_id, full_name, phone, about, contact_email, created_at, updated_at, deleted_at
`

type QueryUpsertProfileParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	FullName     string      `json:"full_name"`
	Phone        pgtype.Text `json:"phone"`
	About        pgtype.Text `json:"about"`
	ContactEmail pgtype.Text `json:"contact_email"`
}

func (q *Queries) QueryUpsertProfile(ctx context.Context, arg QueryUpsertProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, queryUpsertProfile,
		arg.UserID,
		arg.FullName,
		arg.Phone,
		arg.About,
		arg.ContactEmail,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.FullName,
		&i.Phone,
		&i.About,
		&i.ContactEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

// ── Paginated list queries (manually written — sqlc cannot be re-run) ──

const queryListExperiences = `
SELECT id, user_id, company_name, job_role, description, is_current_job,
       start_date, end_date, tech_stack, achievements, tags,
       created_at, updated_at, deleted_at,
       COUNT(*) OVER() AS total_count
FROM user_experiences
WHERE user_id = $1 AND deleted_at IS NULL
  AND ($2::TEXT IS NULL OR (company_name ILIKE '%' || $2 || '%' OR job_role ILIKE '%' || $2 || '%'))
ORDER BY start_date DESC
LIMIT $4 OFFSET $3
`

type QueryListExperiencesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Search pgtype.Text `json:"search"`
	Cursor int32       `json:"cursor"`
	Size   int32       `json:"size"`
}

type QueryListExperiencesRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	CompanyName  string             `json:"company_name"`
	JobRole      string             `json:"job_role"`
	Description  pgtype.Text        `json:"description"`
	IsCurrentJob bool               `json:"is_current_job"`
	StartDate    pgtype.Date        `json:"start_date"`
	EndDate      pgtype.Date        `json:"end_date"`
	TechStack    []string           `json:"tech_stack"`
	Achievements []string           `json:"achievements"`
	Tags         []string           `json:"tags"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	TotalCount   int64              `json:"total_count"`
}

func (q *Queries) QueryListExperiences(ctx context.Context, arg QueryListExperiencesParams) ([]QueryListExperiencesRow, error) {
	rows, err := q.db.Query(ctx, queryListExperiences, arg.UserID, arg.Search, arg.Cursor, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryListExperiencesRow
	for rows.Next() {
		var i QueryListExperiencesRow
		if err := rows.Scan(
			&i.ID, &i.UserID, &i.CompanyName, &i.JobRole, &i.Description,
			&i.IsCurrentJob, &i.StartDate, &i.EndDate, &i.TechStack, &i.Achievements,
			&i.Tags, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt, &i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const queryListAcademicHistories = `
SELECT id, user_id, institution_name, course_name, start_date, end_date, description,
       created_at, updated_at, deleted_at,
       COUNT(*) OVER() AS total_count
FROM user_academic_histories
WHERE user_id = $1 AND deleted_at IS NULL
  AND ($2::TEXT IS NULL OR (institution_name ILIKE '%' || $2 || '%' OR course_name ILIKE '%' || $2 || '%'))
ORDER BY start_date DESC
LIMIT $4 OFFSET $3
`

type QueryListAcademicHistoriesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Search pgtype.Text `json:"search"`
	Cursor int32       `json:"cursor"`
	Size   int32       `json:"size"`
}

type QueryListAcademicHistoriesRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	InstitutionName string             `json:"institution_name"`
	CourseName      string             `json:"course_name"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	Description     pgtype.Text        `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	TotalCount      int64              `json:"total_count"`
}

func (q *Queries) QueryListAcademicHistories(ctx context.Context, arg QueryListAcademicHistoriesParams) ([]QueryListAcademicHistoriesRow, error) {
	rows, err := q.db.Query(ctx, queryListAcademicHistories, arg.UserID, arg.Search, arg.Cursor, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryListAcademicHistoriesRow
	for rows.Next() {
		var i QueryListAcademicHistoriesRow
		if err := rows.Scan(
			&i.ID, &i.UserID, &i.InstitutionName, &i.CourseName,
			&i.StartDate, &i.EndDate, &i.Description,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt, &i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const queryListSkills = `
SELECT id, user_id, skill_name, proficiency_level, tags,
       created_at, updated_at, deleted_at,
       COUNT(*) OVER() AS total_count
FROM user_skills
WHERE user_id = $1 AND deleted_at IS NULL
  AND ($2::TEXT IS NULL OR skill_name ILIKE '%' || $2 || '%')
ORDER BY skill_name
LIMIT $4 OFFSET $3
`

type QueryListSkillsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Search pgtype.Text `json:"search"`
	Cursor int32       `json:"cursor"`
	Size   int32       `json:"size"`
}

type QueryListSkillsRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	SkillName        string             `json:"skill_name"`
	ProficiencyLevel SkillLevel         `json:"proficiency_level"`
	Tags             []string           `json:"tags"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	TotalCount       int64              `json:"total_count"`
}

func (q *Queries) QueryListSkills(ctx context.Context, arg QueryListSkillsParams) ([]QueryListSkillsRow, error) {
	rows, err := q.db.Query(ctx, queryListSkills, arg.UserID, arg.Search, arg.Cursor, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryListSkillsRow
	for rows.Next() {
		var i QueryListSkillsRow
		if err := rows.Scan(
			&i.ID, &i.UserID, &i.SkillName, &i.ProficiencyLevel, &i.Tags,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt, &i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const queryListProjects = `
SELECT id, user_id, project_name, description, project_url, tags,
       start_date, end_date, is_academic,
       created_at, updated_at, deleted_at,
       COUNT(*) OVER() AS total_count
FROM user_projects
WHERE user_id = $1 AND deleted_at IS NULL
  AND ($2::TEXT IS NULL OR project_name ILIKE '%' || $2 || '%')
ORDER BY start_date DESC
LIMIT $4 OFFSET $3
`

type QueryListProjectsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Search pgtype.Text `json:"search"`
	Cursor int32       `json:"cursor"`
	Size   int32       `json:"size"`
}

type QueryListProjectsRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ProjectName string             `json:"project_name"`
	Description string             `json:"description"`
	ProjectUrl  pgtype.Text        `json:"project_url"`
	Tags        []string           `json:"tags"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	IsAcademic  bool               `json:"is_academic"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	TotalCount  int64              `json:"total_count"`
}

func (q *Queries) QueryListProjects(ctx context.Context, arg QueryListProjectsParams) ([]QueryListProjectsRow, error) {
	rows, err := q.db.Query(ctx, queryListProjects, arg.UserID, arg.Search, arg.Cursor, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryListProjectsRow
	for rows.Next() {
		var i QueryListProjectsRow
		if err := rows.Scan(
			&i.ID, &i.UserID, &i.ProjectName, &i.Description, &i.ProjectUrl, &i.Tags,
			&i.StartDate, &i.EndDate, &i.IsAcademic,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt, &i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const queryListCertificates = `
SELECT id, user_id, certificate_name, issuing_organization, issue_date, credential_url, tags,
       created_at, updated_at, deleted_at,
       COUNT(*) OVER() AS total_count
FROM user_certificates
WHERE user_id = $1 AND deleted_at IS NULL
  AND ($2::TEXT IS NULL OR (certificate_name ILIKE '%' || $2 || '%' OR issuing_organization ILIKE '%' || $2 || '%'))
ORDER BY issue_date DESC
LIMIT $4 OFFSET $3
`

type QueryListCertificatesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Search pgtype.Text `json:"search"`
	Cursor int32       `json:"cursor"`
	Size   int32       `json:"size"`
}

type QueryListCertificatesRow struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	CertificateName     string             `json:"certificate_name"`
	IssuingOrganization string             `json:"issuing_organization"`
	IssueDate           pgtype.Date        `json:"issue_date"`
	CredentialUrl       pgtype.Text        `json:"credential_url"`
	Tags                []string           `json:"tags"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	TotalCount          int64              `json:"total_count"`
}

func (q *Queries) QueryListCertificates(ctx context.Context, arg QueryListCertificatesParams) ([]QueryListCertificatesRow, error) {
	rows, err := q.db.Query(ctx, queryListCertificates, arg.UserID, arg.Search, arg.Cursor, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryListCertificatesRow
	for rows.Next() {
		var i QueryListCertificatesRow
		if err := rows.Scan(
			&i.ID, &i.UserID, &i.CertificateName, &i.IssuingOrganization,
			&i.IssueDate, &i.CredentialUrl, &i.Tags,
			&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt, &i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
