// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const workerInsertGeneratedResume = `-- name: WorkerInsertGeneratedResume :one
INSERT INTO generated_resumes(job_id, user_id, content_json)
VALUES ($1, $2, $3)
RETURNING id
`

type WorkerInsertGeneratedResumeParams struct {
	JobID       pgtype.UUID `json:"job_id"`
	UserID      pgtype.UUID `json:"user_id"`
	ContentJson []byte      `json:"content_json"`
}

func (q *Queries) WorkerInsertGeneratedResume(ctx context.Context, arg WorkerInsertGeneratedResumeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, workerInsertGeneratedResume, arg.JobID, arg.UserID, arg.ContentJson)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const workerSelectPendingJobs = `-- name: WorkerSelectPendingJobs :many


SELECT j.id, j.user_id, j.external_url, j.company_name, j.job_title, j.description, j.tech_stack, j.requirements, j.status, j.quality, j.language, j.created_at, j.updated_at, j.deleted_at
FROM jobs j
INNER JOIN user_accounts acc ON acc.id = j.user_id
WHERE
    j.status = 'pending' AND
    j.deleted_at IS NULL AND
    acc.deleted_at IS NULL
ORDER BY j.created_at
LIMIT $1
`

// =============================================================================
// WORKER QUERIES
// Queries exclusivas do worker interno. Sem validação de user_id pois o worker
// é um processo confiável que opera sobre qualquer job da pipeline.
// NÃO exponha estas queries via API.
// =============================================================================
func (q *Queries) WorkerSelectPendingJobs(ctx context.Context, maxCount int32) ([]Job, error) {
	rows, err := q.db.Query(ctx, workerSelectPendingJobs, maxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExternalUrl,
			&i.CompanyName,
			&i.JobTitle,
			&i.Description,
			&i.TechStack,
			&i.Requirements,
			&i.Status,
			&i.Quality,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workerUpdateJob = `-- name: WorkerUpdateJob :exec
UPDATE jobs
SET
    company_name = $1,
    job_title    = $2,
    description  = $3,
    tech_stack   = $4,
    requirements = $5,
    language     = $6,
    updated_at   = now()
WHERE id = $7
`

type WorkerUpdateJobParams struct {
	CompanyName  pgtype.Text `json:"company_name"`
	JobTitle     pgtype.Text `json:"job_title"`
	Description  pgtype.Text `json:"description"`
	TechStack    []string    `json:"tech_stack"`
	Requirements []string    `json:"requirements"`
	Language     pgtype.Text `json:"language"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) WorkerUpdateJob(ctx context.Context, arg WorkerUpdateJobParams) error {
	_, err := q.db.Exec(ctx, workerUpdateJob,
		arg.CompanyName,
		arg.JobTitle,
		arg.Description,
		arg.TechStack,
		arg.Requirements,
		arg.Language,
		arg.ID,
	)
	return err
}

const workerUpdateJobQuality = `-- name: WorkerUpdateJobQuality :exec
UPDATE jobs
SET
    quality    = $1,
    updated_at = now()
WHERE id = $2
`

type WorkerUpdateJobQualityParams struct {
	Quality NullJobQuality `json:"quality"`
	ID      pgtype.UUID    `json:"id"`
}

func (q *Queries) WorkerUpdateJobQuality(ctx context.Context, arg WorkerUpdateJobQualityParams) error {
	_, err := q.db.Exec(ctx, workerUpdateJobQuality, arg.Quality, arg.ID)
	return err
}

const workerUpdateJobStatus = `-- name: WorkerUpdateJobStatus :exec
UPDATE jobs
SET
    status     = $1,
    updated_at = now()
WHERE id = $2
`

type WorkerUpdateJobStatusParams struct {
	Status JobStatus   `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) WorkerUpdateJobStatus(ctx context.Context, arg WorkerUpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, workerUpdateJobStatus, arg.Status, arg.ID)
	return err
}
